### ISSUE TITLE
Got an 403 error "Permission denied"

### ISSUE THREAD

**Issue by jtuttas** [google-pay/wallet-web-codelab#1]
Hello, I do exactly what I'am told in the documentation, but I always get an error message (Permission denied). Here is the output after starting *app.js*. Any idea what goes wrong?

````
GaxiosError: Permission denied.
    at Gaxios._request (D:\Temp\wallet-web-codelab\node_modules\gaxios\build\src\gaxios.js:129:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async JWT.requestAsync (D:\Temp\wallet-web-codelab\node_modules\google-auth-library\build\src\auth\oauth2client.js:368:18)
    at async createPassAndToken (D:\Temp\wallet-web-codelab\app.js:42:22) {
  response: {
    config: {
      url: 'https://walletobjects.googleapis.com/walletobjects/v1/genericObject/3388000000022122304.tuttas68_googlemail.com-3388000000022122304.2154c72a-84fb-4871-acdb-d0a7dab21f8f',
      method: 'GET',
      headers: [Object],
      paramsSerializer: [Function: paramsSerializer],
      validateStatus: [Function: validateStatus],
      responseType: 'json'
    },
    data: { error: [Object] },
    headers: {
      'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"',
      'cache-control': 'private',
      connection: 'close',
      'content-encoding': 'gzip',
      'content-type': 'application/json; charset=UTF-8',
      date: 'Wed, 18 May 2022 06:22:49 GMT',
      server: 'ESF',
      'transfer-encoding': 'chunked',
      vary: 'Origin, X-Origin, Referer',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'SAMEORIGIN',
      'x-xss-protection': '0'
    },
    status: 403,
    statusText: 'Forbidden',
    request: {
      responseURL: 'https://walletobjects.googleapis.com/walletobjects/v1/genericObject/3388000000022122304.tuttas68_googlemail.com-3388000000022122304.2154c72a-84fb-4871-acdb-d0a7dab21f8f'
    }
  },
  config: {
    url: 'https://walletobjects.googleapis.com/walletobjects/v1/genericObject/3388000000022122304.tuttas68_googlemail.com-3388000000022122304.2154c72a-84fb-4871-acdb-d0a7dab21f8f',
    method: 'GET',
    headers: {
      Authorization: 'Bearer ya29.c.b0AXv0zTMYp5V-tl9qJDgJmpE5M6Uuh6_cy0Lap8tDGRU1aBlnMqbhMyUDDh_dbiOJes9Sl2iOMJJsePDYxDeevr6K9ZsIt0_mAEsUJ9KzS7gE8ojhzgDNVDKvdJH-kznO9QYAFpCrGkjeScvk80OEaYsAH5Ya8-XAH4BGw_xjrrPQ121sSO3fxUEt8SjJ0BsKCUYVyxqESj_o3og4EQko08CI-DgUOG0........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................',
      'User-Agent': 'google-api-nodejs-client/7.14.1',
      'x-goog-api-client': 'gl-node/16.11.1 auth/7.14.1',
      Accept: 'application/json'
    },
    paramsSerializer: [Function: paramsSerializer],
    validateStatus: [Function: validateStatus],
    responseType: 'json'
  },
  code: 403,
  errors: [
    {
      message: 'Permission denied.',
      domain: 'walletobjects',
      reason: 'permissionDenied'
    }
  ]
}
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

GaxiosError: Permission denied.
    at Gaxios._request (D:\Temp\wallet-web-codelab\node_modules\gaxios\build\src\gaxios.js:129:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async JWT.requestAsync (D:\Temp\wallet-web-codelab\node_modules\google-auth-library\build\src\auth\oauth2client.js:368:18)
    at async createPassAndToken (D:\Temp\wallet-web-codelab\app.js:42:22) {
  response: {
    config: {
      url: 'https://walletobjects.googleapis.com/walletobjects/v1/genericObject/3388000000022122304.tuttas68_googlemail.com-3388000000022122304.2154c72a-84fb-4871-acdb-d0a7dab21f8f',
      method: 'GET',
      headers: {
        Authorization: 'Bearer ya29.c.b0AXv0zTMYp5V-tl9qJDgJmpE5M6Uuh6_cy0Lap8tDGRU1aBlnMqbhMyUDDh_dbiOJes9Sl2iOMJJsePDYxDeevr6K9ZsIt0_mAEsUJ9KzS7gE8ojhzgDNVDKvdJH-kznO9QYAFpCrGkjeScvk80OEaYsAH5Ya8-XAH4BGw_xjrrPQ121sSO3fxUEt8SjJ0BsKCUYVyxqESj_o3og4EQko08CI-DgUOG0........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................',
        'User-Agent': 'google-api-nodejs-client/7.14.1',
        'x-goog-api-client': 'gl-node/16.11.1 auth/7.14.1',
        Accept: 'application/json'
      },
      paramsSerializer: [Function: paramsSerializer],
      validateStatus: [Function: validateStatus],
      responseType: 'json'
    },
    data: {
      error: {
        code: 403,
        message: 'Permission denied.',
        errors: [
          {
            message: 'Permission denied.',
            domain: 'walletobjects',
            reason: 'permissionDenied'
          }
        ]
      }
    },
    headers: {
      'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"',
      'cache-control': 'private',
      connection: 'close',
      'content-encoding': 'gzip',
      'content-type': 'application/json; charset=UTF-8',
      date: 'Wed, 18 May 2022 06:22:49 GMT',
      server: 'ESF',
      'transfer-encoding': 'chunked',
      vary: 'Origin, X-Origin, Referer',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'SAMEORIGIN',
      'x-xss-protection': '0'
    },
    status: 403,
    statusText: 'Forbidden',
    request: {
      responseURL: 'https://walletobjects.googleapis.com/walletobjects/v1/genericObject/3388000000022122304.tuttas68_googlemail.com-3388000000022122304.2154c72a-84fb-4871-acdb-d0a7dab21f8f'
    }
  },
  config: {
    url: 'https://walletobjects.googleapis.com/walletobjects/v1/genericObject/3388000000022122304.tuttas68_googlemail.com-3388000000022122304.2154c72a-84fb-4871-acdb-d0a7dab21f8f',
    method: 'GET',
    headers: {
      Authorization: 'Bearer ya29.c.b0AXv0zTMYp5V-tl9qJDgJmpE5M6Uuh6_cy0Lap8tDGRU1aBlnMqbhMyUDDh_dbiOJes9Sl2iOMJJsePDYxDeevr6K9ZsIt0_mAEsUJ9KzS7gE8ojhzgDNVDKvdJH-kznO9QYAFpCrGkjeScvk80OEaYsAH5Ya8-XAH4BGw_xjrrPQ121sSO3fxUEt8SjJ0BsKCUYVyxqESj_o3og4EQko08CI-DgUOG0........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................',
      'User-Agent': 'google-api-nodejs-client/7.14.1',
      'x-goog-api-client': 'gl-node/16.11.1 auth/7.14.1',
      Accept: 'application/json'
    },
    paramsSerializer: [Function: paramsSerializer],
    validateStatus: [Function: validateStatus],
    responseType: 'json'
  },
  code: 403,
  errors: [
    {
      message: 'Permission denied.',
      domain: 'walletobjects',
      reason: 'permissionDenied'
    }
  ]
}
```

**Comment by chrishenschel** [comment]
`// https://codelabs.developers.google.com/add-to-wallet-web
// use the same email-address to generate the temporary user as in key.json
const serviceAccountFile = './key.json';
const issuerId = '123456xxxxxxxxxx';
const classId = '12asdsadsd-abcdefgh-abcdef-abcdefghijklm'; // remove the leading issuerId and dot here`

**Comment by jtuttas** [comment]
YEAH, Perfect this is the solution !

**Comment by Songkeys** [comment]
> Check that you use the same "client_email" for the Temporary Issuer account which you have listed in the key.json

Sorry. Could you please be more specific? What does it mean by "same email address"? Same as what? My service account is something like `xxxxxx@xxxxxxxx-12345.iam.gserviceaccount.com`. I downloaded the `key.json` from the console. It's 403 for me.
