### ISSUE TITLE
Issuer Id and Invalid resource Id 

### ISSUE THREAD

**Issue by Viper-ui** [google-pay/wallet-web-codelab#13]
Is the issuer the Client Id mentiond in the JSON key path file that we have or not?

And if so I am getting a invalid resource ID error while providing the issuer id getting the below error:
could you plzz analyze the error if I am missing something?

GaxiosError: Invalid resource ID: 106059277452033318578.codelab_class
at Gaxios.request (D:\NodeJs\google-paywallet-web-codelab\wallet-web-codelab\web\node_modules\gaxios\build\src\gaxios.js:129:23)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async JWT.requestAsync (D:\NodeJs\google-paywallet-web-codelab\wallet-web-codelab\web\node_modules\google-auth-library\build\src\auth\oauth2client.js:368:18)
at async createPassClass (D:\NodeJs\google-paywallet-web-codelab\wallet-web-codelab\web\app.js:144:16)
at async D:\NodeJs\google-paywallet-web-codelab\wallet-web-codelab\web\app.js:236:3 {
response: {
config: {
url: 'https://walletobjects.googleapis.com/walletobjects/v1/genericClass/106059277452033318578.codelab_class',
method: 'GET',
headers: [Object],
paramsSerializer: [Function: paramsSerializer],
validateStatus: [Function: validateStatus],
responseType: 'json'
},
data: { error: [Object] },
headers: {
'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000',
'cache-control': 'private',
connection: 'close',
'content-encoding': 'gzip',
'content-type': 'application/json; charset=UTF-8',
date: 'Tue, 07 Mar 2023 10:11:54 GMT',
server: 'ESF',
'transfer-encoding': 'chunked',
vary: 'Origin, X-Origin, Referer',
'x-content-type-options': 'nosniff',
'x-frame-options': 'SAMEORIGIN',
'x-xss-protection': '0'
},
status: 400,
statusText: 'Bad Request',
request: {
responseURL: 'https://walletobjects.googleapis.com/walletobjects/v1/genericClass/106059277452033318578.codelab_class'
}
},
config: {
url: 'https://walletobjects.googleapis.com/walletobjects/v1/genericClass/106059277452033318578.codelab_class',
method: 'GET',
headers: {
Authorization: 'Bearer ya29.c.b0Aaekm1LA2INE9TsZZiyfTUfS24kp7BJK6Ho55zp2nAHiql5XWAnFBn054ycw7bkrAZs6AIi_eXgbWfEIhhwbsELYBGyAghMtBhFdDFSkQY0kjN7f0JQkuUkdL3T_zr5jfsaRsISazvgLceHCytrX2VCDdj-5Vxs539ilTqVXl1fjbdUxDSMI3lBLK3b90Hn4Vw7_gKeRm2q3aS6Devjut95CXV5kvVU7LPHmwpOa7vlZdTYB7TO6hhyAcLvuPQ_bmonlsOwJvHjSoEkRo2iMOlTcpTp4YshI2km9-vlfRbAIzexZZrA711mXvbDvR-2E-CkUTeZfT337Pa4r4RebYFx4zsdt1gi93v-uqcJ8f1M1gVpf_i-OV2gSp8ojwxUdzkppbXrrc7OzmYQ7_unom1QQqpj6nOiFo0QOmjSonRv76WtY-3aMr__w_u8uc5Yypuqpeabgo00apIqcocffRZqYXQeVQkZBcQqMBcBjrVaf91rI_JYlBVYZ96OmQUuY1U1ZkY_hQ1BJ3SMffcaM3U-vhdzs344mvyiRMQyaoUgsttX3VXtR49qsxRIIx7IIl-962VnFFQXYFX_4ynaUgayXqIWpnkQzrXymwRIUR4gtblyRX0r4sIq7horUnypJx7Wzko7Ri_jVlqJR1BBsBW1M-bWqYfUlXOtdljjp0i7rmk3x8uoaRS8FhcU8FtQXiVp-WXx59UrVs6Qedu_Mhov04vdxJ-bhoIccRZz3V1MeiUXfdMYwc4Z5WsJv9QO4lBWynkp01gYVVU98B34q8sJzidVZO0Yl4_7OdzSVMwF4eg6w0q9aSetli4ad2bbg4W-7OcO3ybodwR4iQVmiqbivBVbcfonh1YVOhaqM61YpW5XQOhY5RV29JZB6IR0ukl8qhllceYB8i8WMl1RrdtriWy_0h8xzOpzcjOvWVZb4f_UmZjrSkM_9e2yXcUVFr8Szjnwu5Qdcv2mF3Wq65oSYV88Jdn2-uvaO0vuSgSQpczw8y_m8W6',
'User-Agent': 'google-api-nodejs-client/7.14.1',
'x-goog-api-client': 'gl-node/14.21.1 auth/7.14.1',
Accept: 'application/json'
},
paramsSerializer: [Function: paramsSerializer],
validateStatus: [Function: validateStatus],
responseType: 'json'
},
code: 400,
errors: [
{
message: 'Invalid resource ID: 106059277452033318578.codelab_class',
domain: 'walletobjects',
reason: 'invalidResource'
}
]
}

**Comment by Viper-ui** [comment]
Hi @stephenmcd  I got it as the business profile was not setup for my id ...I was unable to get the Id .....anyways thanks for the information.
